In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

In [166]:
def distance(a,b):
    return np.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2)

def create(size):
    M = np.ones(shape=(size,size))
    return M

def big_matrix(M):                                 #warning: can be used just for the initialization, not when we introduce displacements
    A = np.ones(shape=(2*len(M),2*len(M)))
    return A
'''
def big_matrix_general(M):
    l = len(M)
    A = [][2*l]
    while i < 2*l-1:
        while j < l/4 :
            A[i][j] = M[]
'''       
    
def x_0(size):
    x = random.uniform(L/2,3*L/2)
    y = random.uniform(L/2,3*L/2)
    center = [x,y]
    return center

def small_matrix(M,c,r):
    A = M[int(c[1]-r):int(c[1]+r+1),int(c[0]-r-1):int(c[0]+r)]
    return A

def count(small,r):   #check this
    n = 0
    l = len(small)
    c = [(l+1)/2,(l+1)/2]
    for i in range(l):
        for j in range(l):
            x = [i,j]
            d = distance(x,c)
            if d <= r :
                n += 1
    return n

def arr_counts(size,n,R,big):
    arr = []
    for i in range(n):
        center = x_0(size)
        small = small_matrix(big, center, R)
        arr.append(count(small,center,R))
    return arr

def variance(arr_counts):
    mom = np.power(arr_counts,2)
    return np.average(mom)-np.average(arr_counts)**2

def create_prova(L):
    A = np.arange(L**2).reshape((L, L))
    return A

In [185]:
#debug
L = 10
A = create_prova(L)
B = big_matrix(A)
point = x_0(L)
print(point)
A

[14.23823860410746, 7.305681140488602]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
#dovrebbe prendere da 31 a 75
#c = [5,5]
r = 5
S = small_matrix(B,point,r)
print(S)
count(S,r)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


79

L = 10
M = create(L)
big = big_matrix(L,M)
plt.figure(figsize=(5, 5))
plt.spy(big, markersize=10, marker = '.')

In [ ]:
center = x_0(L)
print(center)
r = 3
#count(small,center,r)
x = arr_counts(L,1000,r,big)
plt.plot(x)

In [ ]:
c = x_0(L)
print(c)
small = small_matrix(big, c, r)
print(small)
print(len(small[0]))
count(small,c,r)